"use client";

import {Button, Card, Typography} from "antd";
import {AlignRightOutlined, DownloadOutlined, FilterOutlined} from "@ant-design/icons";
import {BarChart, PieChart} from "@mui/x-charts";

const {Title} = Typography


// autogenerated
interface GraphsViewProps {
  covidCases?: Array<{ id: number; city: string; date: Date; amount: number; createdAt: Date; updatedAt: Date }>,
  virusCases?: Array<{ id: number; name: string; date: Date; cases: number; createdAt: Date; updatedAt: Date }>
}

export function GraphsView({covidCases = [], virusCases = []}: GraphsViewProps) {
  const formattedCovidCasesDates = covidCases.map((covidCase) =>
    (covidCase.date.toLocaleDateString()));

  const formattedCovidCasesAmounts = covidCases.map((covidCase) =>
    (covidCase.amount));

  const formattedVirusCases = virusCases.map((virusCase) => ({
    id: virusCase.id,
    value: virusCase.cases,
    label: virusCase.name,
  }))

  return (
    <div className="px-2 py-2 lg:px-20 xl:px-40 lg:py-5 xl:py-10">
      <div className="flex flex-wrap justify-between">
        <Title className="m-0" level={4}>Page title</Title>
        <div className="flex gap-6">
          <Button icon={<DownloadOutlined/>}>
            Export to PDF
          </Button>
          <Button icon={<AlignRightOutlined/>}>
            Notes <span className="text-gray-400">(3)</span>
          </Button>
          <Button icon={<FilterOutlined/>}>
            Filter
          </Button>
        </div>
      </div>

      <div className="flex flex-wrap lg:flex-nowrap justify-center gap-8 pt-4">
        <Card className="w-[500px]" title="Chart title">
          <BarChart
            className="w-10/12"
            xAxis={[
              {
                id: 'barCategories',
                data: formattedCovidCasesDates,
                scaleType: 'band',
              },
            ]}
            series={[
              {
                data: formattedCovidCasesAmounts
              },
            ]}
            height={300}
          />
        </Card>
        <Card className="w-[500px]" title="Chart title" >
          <PieChart
            series={[
              {
                data: formattedVirusCases,
              },
            ]}
            height={200}
          />
        </Card>
      </div>
    </div>
  );
}
